#!/usr/bin/env bash
# Displays the record types of subdomains

show_domain_info () {
    line=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

if [ $# -eq 2 ]
then
    show_domain_info "$1" "$2"
elif [ $# -eq 1 ]
then
    show_domain_info "$1" www
    show_domain_info "$1" lb-01
    show_domain_info "$1" web-01
    show_domain_info "$1" web-02
fi
