#!/usr/bin/env bash
## A bash script to transfer a file from the client to a server
# Accept 4 arguments:
# 1. path to the file to be transfered
# 2. IP ot the server
# 3. username scp connects with
# 4. path to the SSH private key scp uses

if [ $# -lt 3 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~/
fi
