#!/usr/bin/env bash
# A bash script that installs Nginx on my web-01 server
# sets Nginx to listen to port 80
# customizing the GET response to "Hello World!"

sudo apt-get -y update
sudo apt-get -y install nginx
echo 'server {
	listen 80;
	listen [::]:80 default_server;

	root /var/ww/html;
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files $uri $uri/ =404;
		add_header Content-Type text/html;
		add_header Accept-Ranges bytes;
		return 200 "Hello World!\n";
	}
}' | sudo tee /etc/nginx/sites-available/default
sudo service nginx start
