#!/usr/bin/env bash
# A bash script that installs Nginx on my web-01 server
# sets Nginx to listen to port 80
# customizing the GET response to "Hello World!"
# customize the redirection

REDIRECT="s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/injili permanent;/"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i "$REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start
