#!/usr/bin/env bash
# A bash script that installs Nginx on my web-01 server
# sets Nginx to listen to port 80
# customizing the GET response to "Hello World!"
# customize the redirection

REDIRECT="\\\tlocation /redirect_me {\n\t\t return 301 https://google.com;\n\t}\n"

sudo apt-get -y update
sudo apt-get -y install nginx
sudo sh -c "echo 'Hello World!' > /var/www/html/index.nginx-debian.html"
sudo sed -i "30i $REDIRECT" /etc/nginx/sites-available/default
sudo service nginx start
