#!/usr/bin/env bash
# The script to install and configure HAproxy

# install HAproxy
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.0
sudo apt-get -y update
sudo apt-get install -y haproxy=2.0\*

# configure HAproxy to send traffic to web-01 and web-02
sudo tee /etc/haproxy/haproxy.cfg << EOF

frontend Local_Server
	bind *:80
	mode http
	default_backend Web_Server

backend Web_Server
	balance roundrobin
	mode http
	server web-01 54.90.16.200:80 check
	server web-02 34.204.61.165:80 check

EOF

# restart the server
sudo service haproxy restart
