#!/usr/bin/env bash
# Create a compressed archive for all MySQL databse
# Usage: 5-mysql_backup <MySQL password>
mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$(date +%d-%m-%Y)".tar.gz backup.sql
