#!/usr/bin/bash
# A script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root --all-databases -p"$1" > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
