#!/usr/bin/env bash
# Correction of port 80 error

mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default
service nginx stop
pkill nginx
service nginx start
