#!/usr/bin/env bash
# a Bash script that:
# Creates the file /var/run/myscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/myscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

echo "$$" > /var/run/myscript.pid
msg()
{
	echo "I hate the kill command"
}
trap "msg" SIGTERM

msg1()
{
	echo "Y U no love me?!"
}
trap "msg1" SIGINT

msg3()
{
	rm /var/run/myscript.pid
	^C
}
trap "msg2" SIGQUIT

while true;
do
	echo To infinity and beyond
done
