#!/usr/bin/env bash
# numbers from 1 to 20
# 4 then bad luck from China
# 9 then bad luck from Japan
# 17 then bad luck from Italy

x=1
while [ $x -le 20 ]
do
	echo $x
	if [ $x == 4 ]; then
		echo bad luck from China
	elif [ $x == 9 ]; then
		echo bad luck from Japan
	elif [ $x == 17 ]; then
		echo bad luck from Italy
	else
		x=$(( x + 1))
		continue
	fi

	x=$(( x + 1 ))
done
