#!/usr/bin/env bash
# numbers from 1 to 20
# 4 then bad luck from China
# 9 then bad luck from Japan
# 17 then bad luck from Italy

x=1
while [ $x -le 20 ]
do
	echo $x
	case $x in
		4) echo bad luck from China ;;
		9) echo bad luck from Japan ;;
		17) echo bad luck from Italy ;;
	esac
	(( x++ ))
done
