#!/usr/bin/env bash
# a Bash script that displays:
# The contents of the current directory
# In a list format
# Where only the part of the name after the first dash is displayed

files="$(ls)"
for i in $files;
do
	echo "$i" | cut -d "-" -f2
done
