#!/usr/bin/env bash
# a Bash script that gives information about the "school" file

f="school"
if [ -e "$f" ];then
	echo "$f file exists"

	if [ -s "$f" ];then
		echo "$f file is not empty"
	else
		echo "$f file is empty"
	fi

	if [ -f "$f" ];then
		echo "$f is a regular file"
	fi

else
	echo "$f file does not exist"
fi
